application:
  version: v1.0.0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mybatis_plus?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root

#打印sql日志  可以在控制台查看sql语句的日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off #关闭mybatis_plus的启动图标
  mapper-locations: classpath:com/zty/mybatis_plus/mapper/maps/*.xml,classpath:com/zty/mybatis_plus/mapper/*/*.xml #配置mapper xml文件的路径
